### PR TITLE
Fix: >create kqueue: function not implemented< on OpenBSD

### PR DESCRIPTION
**Pull request by c0dev0id**
Hi,

```
$ clidle
clidle: create kqueue: function not implemented
$ 11;rgb:0b0b/0b0b/0b0b
```

clidle is currently crashig due to some syscall changes on OpenBSD. This has been fixed in the sys module, which is a dependency to the ssh module used here.

Can we please update the ssh module to get to the fixed sys module?

Clidle is still working fine over ssh with the update.

### CODE REVIEW

**Comment by c0dev0id** [comment]
\*ping\*

**Comment by c0dev0id** [comment]
\*ping\*

**Comment by c0dev0id** [comment]
\*ping\* @ajeetdsouza

**Comment by ajeetdsouza** [comment]
Thanks!

**Pull request merged**
